config/routes.rb
Rails.application.routes.draw do
  root "static_page#home"

  resources :artists do
    resources :songs
  end

  resources :billboards do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :genre)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [ :show, :edit, :update, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(bill_params)

    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @billboard.update(bill_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.songs.update_all(billboard_id: nil)
    @billboard.destroy
    redirect_to billboards_path
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def bill_params
      params.require(:billboard).permit(:name, :genre)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_path(@artist)
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :genre, :billboard_id)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Artist Name", autofocus: true %>

    <%= f.label :genre %>
    <%= f.text_field :genre, required: true, placeholder: "Music Genre"%>

    <%= f.submit nil, class:"ui button green"%>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", artist: @artist %>

<%= link_to 'Show', artist_path(@artist) %>
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1 class="home_header">Artists</h1>
<hr>
  <%= link_to "Create Artist", new_artist_path %>
<hr>
<% @artists.each do |artist| %>
  <hr>
  <h3> <%= artist.name %> </h3>
  <%= link_to "Show Artist", artist_path(artist) %>
  <br>
  <%= link_to "Edit Artist", edit_artist_path(artist) %>
  <br>
  <%= link_to "Delete Artist", artist, method: :delete %>
  <hr>
<% end %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", artist: @artist %>
<br />
<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<h4><%= @artist.genre%></h4>
<hr>
<%= link_to "View Songs", artist_songs_path(@artist) %>
<ul>
  <% @artist.songs.each do |song| %>
    <li><%= song.name %></li>
  <% end %>
  </ul>
<hr>

app/views/billboards/_form.html.erb
<%= form_with(model: billboard, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Billboard Name", autofocus: true %>

    <%= f.label :genre %>
    <%= f.text_field :genre, required: true, placeholder: "Genre" %>

    <%= f.submit nil, class:"ui button green"%>
  </div>
<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Billboard</h1>

<%= render "form", billboard: @billboard %>

<%= link_to 'Show', billboard_path(@billboard) %>
<%= link_to 'Back', billboards_path %>

app/views/billboards/index.html.erb
<h1 class="home_header">Billboards</h1>
<hr>
  <%= link_to "Create Billboard", new_billboard_path %>
<hr>
<% @billboards.each do |billboard| %>
  <hr>
  <h3> <%= billboard.name %> </h3>
  <%= link_to "Show Billboard", billboard_path(billboard) %>
  <br>
  <%= link_to "Edit Billboard", edit_billboard_path(billboard) %>
  <br>
  <%= link_to "Delete Billboard", billboard, method: :delete %>
  <hr>
<% end %>

app/views/billboards/new.html.erb
<h1>New Billboard</h1>

<%= render "form", billboard: @billboard %>
<br />
<%= link_to 'Back', billboards_path %>

app/views/billboards/show.html.erb
<h1>Top 10 House</h1>
<hr>
  <ul>
  <% @billboard.songs.each do |song| %>
    <li><%= song.name %></li>
  <% end %>
  </ul>

app/views/layouts/_navbar.html.erb
<div class="ui inverted menu">
  <%= link_to "Home", root_path, class: "item" %>
  <%= link_to "Billboards", billboards_path, class: "item" %>
  <%= link_to "Artists", artists_path, class: "item" %>
  <div class="ui inverted right menu">
    <button class="item">Log in</button>
    <button class="item">Sign up</button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar"%>
    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Song Name", autofocus: true %>

    <%= f.label :genre %>
    <%= f.text_field :genre, required: true, placeholder: "Music Genre"%>

    <%= f.label :billboard_id %>
    <%= f.number_field :billboard_id %>

    <%= f.submit nil, class:"ui button green"%>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form", song: [@artist, @song] %>

<%= link_to 'Show', artist_song_path(@artist, @song) %>
<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/index.html.erb
<h1>Songs</h1>
<hr>
  <%= link_to "Create Song", new_artist_song_path(@artist) %>
<hr>
<% @songs.each do |song| %>
  <hr>
  <h3>Song: <%= song.name %> </h3>
  <h5>Genre: <%= song.genre%> </h5>
  <%= link_to "Edit Song", edit_artist_song_path(@artist, song) %>
  <br>
  <%= link_to "Delete Song", artist_song_path(@artist, song), method: :delete %>
  <hr>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form", song: [@artist, @song] %>

<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>

<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/static_page/home.html.erb
<h1 class="home_header">Music Billboards</h1>
<%= image_tag 'home_img.jpg', class: "ui fluid image"%>